import Header from "@/components/header/header";
import "./globals.css";
import { Inter } from "next/font/google";
import ThemeProviders from "@/components/themeprovide/provider";
import ReactQueryProvider from "@/providers/reactQuery";
import { NextAuthProvider } from "@/providers/nextAuth";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <ReactQueryProvider>
            <ThemeProviders>
              <Header />
              {children}
              <Toaster />
            </ThemeProviders>
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
